##SoilDataPlottingFunction##
#This function takes a dataframe of soil data organized by landuse and depth, which is generated by the soil_stats() function.
#***DAN: what does "organized by landuse and depth" mean, precisely? Often to specify a data frame precisely it is good practice to 
#say what the column names are what information they contain, and then to say "there is one row for each X" where you say what X is.
#The function runs a loop over the datacolumns which plots the response variable vs. depth for each land use on a line plot.
#***DAN: I did not understand what the above line was saying
#It returns a plot for each response variable. 
#***DAN: what kind of plot, precisely? Showing what against what?

#Args
#soilDat : this is a dataframe containing environmental data. It has sample site categories--landuse and sampling depth, and columns of response variables.
#***DAN: this is clear!
#...: allows the user to specify plot design and specific graph features

soil_plot <- function(soilDat,...)
{
  #for(responseCol in soilDat)
  #{
    #plot(responseLandUse1 ~ soilDepth, include SE bars,...)
    #line(responseLandUse2 ~ soilDepth, include SE bars,...)
  #}
  #return(soilPlot)
#}

  #note: this function may require installing ggplot2  