##SoilDataPlottingFunction##
#This function takes a dataframe of soil data organized by landuse and depth, which is generated by the soil_stats() function.
#The function runs a loop over the datacolumns which plots the response variable vs. depth for each land use on a line plot.
#It returns a plot for each response variable. 


#Args
#soilDat : this is a dataframe containing environmental data. It has sample site categories--landuse and sampling depth, and columns of response variables.
#...: allows the user to specify plot design and specific graph features

soil_plot <- function(soilDat,...)
{
  #for(responseCol in soilDat)
  #{
    #plot(responseLandUse1 ~ soilDepth, include SE bars,...)
    #line(responseLandUse2 ~ soilDepth, include SE bars,...)
  #}
  #return(soilPlot)
#}

  #note: this function may require installing ggplot2  